{"uuid": "2a54a7da-fb8e-4479-8d51-2ad284cd309a", "children": ["d27ed27c-016b-45b2-b7ed-9dee241cd9a5"], "befores": [{"name": "_Class__pytest_setup_method", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.\n\n", "trace": "  File \"D:\\py_36\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\py_36\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 957, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\py_36\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 783, in call_fixture_func\n    res = next(it)\n  File \"D:\\py_36\\venv\\lib\\site-packages\\_pytest\\python.py\", line 746, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"D:\\py_36\\venv\\lib\\site-packages\\_pytest\\python.py\", line 661, in _call_with_optional_argument\n    func()\n  File \"E:\\app_zhaoonline\\android\\testcase\\test_search.py\", line 15, in setup_method\n    self.searchPage=self.mainPage.gotoSearch()\n  File \"E:\\app_zhaoonline\\android\\page\\MainPage.py\", line 27, in gotoSearch\n    self.find(self._search_button).click()\n  File \"E:\\app_zhaoonline\\android\\page\\BasePage.py\", line 29, in find\n    return self.driver.find_element(*kv)\n  File \"C:\\Python36\\Lib\\site-packages\\appium_python_client-0.48-py3.6.egg\\appium\\webdriver\\webdriver.py\", line 284, in find_element\n    'value': value})['value']\n  File \"C:\\Python36\\Lib\\site-packages\\selenium-3.141.0-py3.6.egg\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python36\\Lib\\site-packages\\appium_python_client-0.48-py3.6.egg\\appium\\webdriver\\errorhandler.py\", line 29, in check_response\n    raise wde\n  File \"C:\\Python36\\Lib\\site-packages\\appium_python_client-0.48-py3.6.egg\\appium\\webdriver\\errorhandler.py\", line 24, in check_response\n    super(MobileErrorHandler, self).check_response(response)\n  File \"C:\\Python36\\Lib\\site-packages\\selenium-3.141.0-py3.6.egg\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1601188900164, "stop": 1601188911987}], "start": 1601188900164, "stop": 1601188912058}